### ISSUE TITLE
[Feature request]: Hide sensors from the list

### ISSUE THREAD

**Issue by SebastianGrans** [UshakovVasilii/gnome-shell-extension-freon#160]
As seen in the screenshot below, I have a lot of sensors which give out bogus reading (e.g. `AUXTIN0-3`). I'd like to be able to hide this from the list. 

It has been mentioned in other 'Issues' that you can remove these by adding `ignore` to the `sensors3.conf`, but I am unable to find these sensor labels in the conf file. 

From `sensors-detect` and `sensors` I can tell they originate from
```
Driver `nct6775':
  * ISA bus, address 0x290
    Chip `Nuvoton NCT6791D Super IO Sensors' (confidence: 9)
```
Even if I comment out that section from `sensors3.conf` they still show up. What ended up working was unloading the kernel module: `modprobe -r nct6775`. I guess there are more elegant ways to do this? 

![Screenshot from 2020-02-13 11-14-45](https://user-images.githubusercontent.com/10030015/74424440-416a6d00-4e52-11ea-861a-896ac5ae3f81.png)

[sensors3.txt](https://github.com/UshakovVasilii/gnome-shell-extension-freon/files/4197690/sensors3.txt)

**Comment by jonasmalacofilho** [comment]
The `ignore` directive has to be used with "raw" sensor names. For example: `ignore temp1`.

To find out the correspondence between a sensor and it's label, try inspecting the output of `sensors -u`.

**Comment by SebastianGrans** [comment]
This is part of what `sensors -u` gave me:
```
nct6791-isa-0290
Adapter: ISA adapter
[...]
AUXTIN0:
  temp3_input: 126.000
  temp3_type: 4.000
  temp3_offset: 0.000
AUXTIN1:
  temp4_input: -128.000
  temp4_type: 4.000
  temp4_offset: 0.000
[...]
```
I then tried adding:
```
ignore temp4_input
label temp3_input "Test"
``` 
under the heading `chip [...] "nct6791-*"` in my `sensors3.conf`. This didn't seem to change anything.
Do I have to reload the configuration somehow? `sensors -c /etc/sensors3.conf` didn't help.
